/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Notes
 * OpenAPI spec version: 0.1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import { customFetch } from './fetch-instance';
export interface HTTPValidationError {
  detail?: ValidationError[];
}

export type NoteAccessRequestPassword = string | null;

export interface NoteAccessRequest {
  password?: NoteAccessRequestPassword;
}

export type NoteContentResponseExpiresAt = string | null;

export interface NoteContentResponse {
  id: string;
  content: string;
  created_at: string;
  expires_at: NoteContentResponseExpiresAt;
  burn_after_reading: boolean;
}

export type NoteCreateRequestPassword = string | null;

export type NoteCreateRequestExpiresInMinutes = number | null;

export interface NoteCreateRequest {
  /**
   * @minLength 1
   * @maxLength 100000
   */
  content: string;
  password?: NoteCreateRequestPassword;
  expires_in_minutes?: NoteCreateRequestExpiresInMinutes;
  burn_after_reading?: boolean;
}

export type NoteCreatedResponseExpiresAt = string | null;

export interface NoteCreatedResponse {
  id: string;
  path: string;
  expires_at: NoteCreatedResponseExpiresAt;
  burn_after_reading: boolean;
}

export type NoteListItemExpiresAt = string | null;

export interface NoteListItem {
  id: string;
  requires_password: boolean;
  burn_after_reading: boolean;
  content_preview?: string;
  created_at: string;
  expires_at: NoteListItemExpiresAt;
}

export type NoteMetadataResponseExpiresAt = string | null;

export interface NoteMetadataResponse {
  id: string;
  requires_password: boolean;
  burn_after_reading: boolean;
  is_owner?: boolean;
  created_at: string;
  expires_at: NoteMetadataResponseExpiresAt;
}

export interface UserResponse {
  id: string;
  email: string;
  name: string;
}

export type ValidationErrorLocItem = string | number;

export type ValidationErrorCtx = { [key: string]: unknown };

export interface ValidationError {
  loc: ValidationErrorLocItem[];
  msg: string;
  type: string;
  input?: unknown;
  ctx?: ValidationErrorCtx;
}

export type HealthCheck200 = {[key: string]: string};

export type GetNoteContentBody = NoteAccessRequest | null;

export type AuthCallbackGoogleParams = {
code?: string | null;
state?: string | null;
error?: string | null;
};

/**
 * Liveness + readiness probe. Returns 503 when the database is unreachable.
 * @summary Health Check
 */
export const healthCheck = (
    
 signal?: AbortSignal
) => {
      
      
      return customFetch<HealthCheck200>(
      {url: `/api/health`, method: 'GET', signal
    },
      );
    }
  



export const getHealthCheckQueryKey = () => {
    return [
    `/api/health`
    ] as const;
    }

    
export const getHealthCheckQueryOptions = <TData = Awaited<ReturnType<typeof healthCheck>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof healthCheck>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getHealthCheckQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof healthCheck>>> = ({ signal }) => healthCheck(signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof healthCheck>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type HealthCheckQueryResult = NonNullable<Awaited<ReturnType<typeof healthCheck>>>
export type HealthCheckQueryError = unknown


export function useHealthCheck<TData = Awaited<ReturnType<typeof healthCheck>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof healthCheck>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof healthCheck>>,
          TError,
          Awaited<ReturnType<typeof healthCheck>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useHealthCheck<TData = Awaited<ReturnType<typeof healthCheck>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof healthCheck>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof healthCheck>>,
          TError,
          Awaited<ReturnType<typeof healthCheck>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useHealthCheck<TData = Awaited<ReturnType<typeof healthCheck>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof healthCheck>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Health Check
 */

export function useHealthCheck<TData = Awaited<ReturnType<typeof healthCheck>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof healthCheck>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getHealthCheckQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * @summary Create Note
 */
export const createNote = (
    noteCreateRequest: NoteCreateRequest,
 signal?: AbortSignal
) => {
      
      
      return customFetch<NoteCreatedResponse>(
      {url: `/api/notes`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: noteCreateRequest, signal
    },
      );
    }
  


export const getCreateNoteMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createNote>>, TError,{data: NoteCreateRequest}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof createNote>>, TError,{data: NoteCreateRequest}, TContext> => {

const mutationKey = ['createNote'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createNote>>, {data: NoteCreateRequest}> = (props) => {
          const {data} = props ?? {};

          return  createNote(data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type CreateNoteMutationResult = NonNullable<Awaited<ReturnType<typeof createNote>>>
    export type CreateNoteMutationBody = NoteCreateRequest
    export type CreateNoteMutationError = HTTPValidationError

    /**
 * @summary Create Note
 */
export const useCreateNote = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createNote>>, TError,{data: NoteCreateRequest}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createNote>>,
        TError,
        {data: NoteCreateRequest},
        TContext
      > => {

      const mutationOptions = getCreateNoteMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    
/**
 * @summary List My Notes
 */
export const listMyNotes = (
    
 signal?: AbortSignal
) => {
      
      
      return customFetch<NoteListItem[]>(
      {url: `/api/notes/my`, method: 'GET', signal
    },
      );
    }
  



export const getListMyNotesQueryKey = () => {
    return [
    `/api/notes/my`
    ] as const;
    }

    
export const getListMyNotesQueryOptions = <TData = Awaited<ReturnType<typeof listMyNotes>>, TError = HTTPValidationError>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listMyNotes>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListMyNotesQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof listMyNotes>>> = ({ signal }) => listMyNotes(signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listMyNotes>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListMyNotesQueryResult = NonNullable<Awaited<ReturnType<typeof listMyNotes>>>
export type ListMyNotesQueryError = HTTPValidationError


export function useListMyNotes<TData = Awaited<ReturnType<typeof listMyNotes>>, TError = HTTPValidationError>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof listMyNotes>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listMyNotes>>,
          TError,
          Awaited<ReturnType<typeof listMyNotes>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListMyNotes<TData = Awaited<ReturnType<typeof listMyNotes>>, TError = HTTPValidationError>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listMyNotes>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listMyNotes>>,
          TError,
          Awaited<ReturnType<typeof listMyNotes>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListMyNotes<TData = Awaited<ReturnType<typeof listMyNotes>>, TError = HTTPValidationError>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listMyNotes>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List My Notes
 */

export function useListMyNotes<TData = Awaited<ReturnType<typeof listMyNotes>>, TError = HTTPValidationError>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listMyNotes>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListMyNotesQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * @summary Get Note Metadata
 */
export const getNoteMetadata = (
    noteId: string,
 signal?: AbortSignal
) => {
      
      
      return customFetch<NoteMetadataResponse>(
      {url: `/api/notes/${noteId}`, method: 'GET', signal
    },
      );
    }
  



export const getGetNoteMetadataQueryKey = (noteId?: string,) => {
    return [
    `/api/notes/${noteId}`
    ] as const;
    }

    
export const getGetNoteMetadataQueryOptions = <TData = Awaited<ReturnType<typeof getNoteMetadata>>, TError = HTTPValidationError>(noteId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getNoteMetadata>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetNoteMetadataQueryKey(noteId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getNoteMetadata>>> = ({ signal }) => getNoteMetadata(noteId, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(noteId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getNoteMetadata>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetNoteMetadataQueryResult = NonNullable<Awaited<ReturnType<typeof getNoteMetadata>>>
export type GetNoteMetadataQueryError = HTTPValidationError


export function useGetNoteMetadata<TData = Awaited<ReturnType<typeof getNoteMetadata>>, TError = HTTPValidationError>(
 noteId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getNoteMetadata>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getNoteMetadata>>,
          TError,
          Awaited<ReturnType<typeof getNoteMetadata>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetNoteMetadata<TData = Awaited<ReturnType<typeof getNoteMetadata>>, TError = HTTPValidationError>(
 noteId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getNoteMetadata>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getNoteMetadata>>,
          TError,
          Awaited<ReturnType<typeof getNoteMetadata>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetNoteMetadata<TData = Awaited<ReturnType<typeof getNoteMetadata>>, TError = HTTPValidationError>(
 noteId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getNoteMetadata>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get Note Metadata
 */

export function useGetNoteMetadata<TData = Awaited<ReturnType<typeof getNoteMetadata>>, TError = HTTPValidationError>(
 noteId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getNoteMetadata>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetNoteMetadataQueryOptions(noteId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * @summary Delete Note
 */
export const deleteNote = (
    noteId: string,
 ) => {
      
      
      return customFetch<void>(
      {url: `/api/notes/${noteId}`, method: 'DELETE'
    },
      );
    }
  


export const getDeleteNoteMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteNote>>, TError,{noteId: string}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof deleteNote>>, TError,{noteId: string}, TContext> => {

const mutationKey = ['deleteNote'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteNote>>, {noteId: string}> = (props) => {
          const {noteId} = props ?? {};

          return  deleteNote(noteId,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteNoteMutationResult = NonNullable<Awaited<ReturnType<typeof deleteNote>>>
    
    export type DeleteNoteMutationError = HTTPValidationError

    /**
 * @summary Delete Note
 */
export const useDeleteNote = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteNote>>, TError,{noteId: string}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteNote>>,
        TError,
        {noteId: string},
        TContext
      > => {

      const mutationOptions = getDeleteNoteMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    
/**
 * Retrieve note content, verifying the password when required.

POST is used intentionally: the password must travel in the request body,
not in the URL (which would appear in server logs and browser history).
 * @summary Get Note Content
 */
export const getNoteContent = (
    noteId: string,
    getNoteContentBody: GetNoteContentBody,
 signal?: AbortSignal
) => {
      
      
      return customFetch<NoteContentResponse>(
      {url: `/api/notes/${noteId}/content`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: getNoteContentBody, signal
    },
      );
    }
  


export const getGetNoteContentMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof getNoteContent>>, TError,{noteId: string;data: GetNoteContentBody}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof getNoteContent>>, TError,{noteId: string;data: GetNoteContentBody}, TContext> => {

const mutationKey = ['getNoteContent'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof getNoteContent>>, {noteId: string;data: GetNoteContentBody}> = (props) => {
          const {noteId,data} = props ?? {};

          return  getNoteContent(noteId,data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type GetNoteContentMutationResult = NonNullable<Awaited<ReturnType<typeof getNoteContent>>>
    export type GetNoteContentMutationBody = GetNoteContentBody
    export type GetNoteContentMutationError = HTTPValidationError

    /**
 * @summary Get Note Content
 */
export const useGetNoteContent = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof getNoteContent>>, TError,{noteId: string;data: GetNoteContentBody}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof getNoteContent>>,
        TError,
        {noteId: string;data: GetNoteContentBody},
        TContext
      > => {

      const mutationOptions = getGetNoteContentMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    
/**
 * @summary Login Google
 */
export const loginGoogle = (
    
 signal?: AbortSignal
) => {
      
      
      return customFetch<unknown>(
      {url: `/api/auth/login/google`, method: 'GET', signal
    },
      );
    }
  



export const getLoginGoogleQueryKey = () => {
    return [
    `/api/auth/login/google`
    ] as const;
    }

    
export const getLoginGoogleQueryOptions = <TData = Awaited<ReturnType<typeof loginGoogle>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof loginGoogle>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getLoginGoogleQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof loginGoogle>>> = ({ signal }) => loginGoogle(signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof loginGoogle>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type LoginGoogleQueryResult = NonNullable<Awaited<ReturnType<typeof loginGoogle>>>
export type LoginGoogleQueryError = unknown


export function useLoginGoogle<TData = Awaited<ReturnType<typeof loginGoogle>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof loginGoogle>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof loginGoogle>>,
          TError,
          Awaited<ReturnType<typeof loginGoogle>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useLoginGoogle<TData = Awaited<ReturnType<typeof loginGoogle>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof loginGoogle>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof loginGoogle>>,
          TError,
          Awaited<ReturnType<typeof loginGoogle>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useLoginGoogle<TData = Awaited<ReturnType<typeof loginGoogle>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof loginGoogle>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Login Google
 */

export function useLoginGoogle<TData = Awaited<ReturnType<typeof loginGoogle>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof loginGoogle>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getLoginGoogleQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * @summary Authcallbackgoogle
 */
export const authCallbackGoogle = (
    params?: AuthCallbackGoogleParams,
 signal?: AbortSignal
) => {
      
      
      return customFetch<unknown>(
      {url: `/api/auth/callback/google`, method: 'GET',
        params, signal
    },
      );
    }
  



export const getAuthCallbackGoogleQueryKey = (params?: AuthCallbackGoogleParams,) => {
    return [
    `/api/auth/callback/google`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getAuthCallbackGoogleQueryOptions = <TData = Awaited<ReturnType<typeof authCallbackGoogle>>, TError = HTTPValidationError>(params?: AuthCallbackGoogleParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof authCallbackGoogle>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getAuthCallbackGoogleQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof authCallbackGoogle>>> = ({ signal }) => authCallbackGoogle(params, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof authCallbackGoogle>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type AuthCallbackGoogleQueryResult = NonNullable<Awaited<ReturnType<typeof authCallbackGoogle>>>
export type AuthCallbackGoogleQueryError = HTTPValidationError


export function useAuthCallbackGoogle<TData = Awaited<ReturnType<typeof authCallbackGoogle>>, TError = HTTPValidationError>(
 params: undefined |  AuthCallbackGoogleParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof authCallbackGoogle>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof authCallbackGoogle>>,
          TError,
          Awaited<ReturnType<typeof authCallbackGoogle>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAuthCallbackGoogle<TData = Awaited<ReturnType<typeof authCallbackGoogle>>, TError = HTTPValidationError>(
 params?: AuthCallbackGoogleParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof authCallbackGoogle>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof authCallbackGoogle>>,
          TError,
          Awaited<ReturnType<typeof authCallbackGoogle>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAuthCallbackGoogle<TData = Awaited<ReturnType<typeof authCallbackGoogle>>, TError = HTTPValidationError>(
 params?: AuthCallbackGoogleParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof authCallbackGoogle>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Authcallbackgoogle
 */

export function useAuthCallbackGoogle<TData = Awaited<ReturnType<typeof authCallbackGoogle>>, TError = HTTPValidationError>(
 params?: AuthCallbackGoogleParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof authCallbackGoogle>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getAuthCallbackGoogleQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * @summary Refresh Token
 */
export const refreshToken = (
    
 signal?: AbortSignal
) => {
      
      
      return customFetch<void>(
      {url: `/api/auth/refresh`, method: 'POST', signal
    },
      );
    }
  


export const getRefreshTokenMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof refreshToken>>, TError,void, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof refreshToken>>, TError,void, TContext> => {

const mutationKey = ['refreshToken'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof refreshToken>>, void> = () => {
          

          return  refreshToken()
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type RefreshTokenMutationResult = NonNullable<Awaited<ReturnType<typeof refreshToken>>>
    
    export type RefreshTokenMutationError = HTTPValidationError

    /**
 * @summary Refresh Token
 */
export const useRefreshToken = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof refreshToken>>, TError,void, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof refreshToken>>,
        TError,
        void,
        TContext
      > => {

      const mutationOptions = getRefreshTokenMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    
/**
 * Return the authenticated user from the access token.
 * @summary Get Current User
 */
export const getCurrentUser = (
    
 signal?: AbortSignal
) => {
      
      
      return customFetch<UserResponse>(
      {url: `/api/auth/me`, method: 'GET', signal
    },
      );
    }
  



export const getGetCurrentUserQueryKey = () => {
    return [
    `/api/auth/me`
    ] as const;
    }

    
export const getGetCurrentUserQueryOptions = <TData = Awaited<ReturnType<typeof getCurrentUser>>, TError = HTTPValidationError>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCurrentUser>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetCurrentUserQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getCurrentUser>>> = ({ signal }) => getCurrentUser(signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getCurrentUser>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetCurrentUserQueryResult = NonNullable<Awaited<ReturnType<typeof getCurrentUser>>>
export type GetCurrentUserQueryError = HTTPValidationError


export function useGetCurrentUser<TData = Awaited<ReturnType<typeof getCurrentUser>>, TError = HTTPValidationError>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCurrentUser>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getCurrentUser>>,
          TError,
          Awaited<ReturnType<typeof getCurrentUser>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetCurrentUser<TData = Awaited<ReturnType<typeof getCurrentUser>>, TError = HTTPValidationError>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCurrentUser>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getCurrentUser>>,
          TError,
          Awaited<ReturnType<typeof getCurrentUser>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetCurrentUser<TData = Awaited<ReturnType<typeof getCurrentUser>>, TError = HTTPValidationError>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCurrentUser>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get Current User
 */

export function useGetCurrentUser<TData = Awaited<ReturnType<typeof getCurrentUser>>, TError = HTTPValidationError>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCurrentUser>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetCurrentUserQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * @summary Logout
 */
export const logout = (
    
 signal?: AbortSignal
) => {
      
      
      return customFetch<void>(
      {url: `/api/auth/logout`, method: 'POST', signal
    },
      );
    }
  


export const getLogoutMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof logout>>, TError,void, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof logout>>, TError,void, TContext> => {

const mutationKey = ['logout'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof logout>>, void> = () => {
          

          return  logout()
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type LogoutMutationResult = NonNullable<Awaited<ReturnType<typeof logout>>>
    
    export type LogoutMutationError = unknown

    /**
 * @summary Logout
 */
export const useLogout = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof logout>>, TError,void, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof logout>>,
        TError,
        void,
        TContext
      > => {

      const mutationOptions = getLogoutMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
